#!/bin/bash

echo ""
echo '                   $$\                                 $$\ '
echo '                   $$ |                                $$ |'
echo '$$\   $$\ $$$$$$\  $$$$$$$\   $$$$$$\  $$\   $$\  $$$$$$$ |'
echo '\$$\ $$  |\____$$\ $$  __$$\  \____$$\ $$ |  $$ |$$  __$$ |'
echo ' \$$$$  / $$$$$$$ |$$ |  $$ | $$$$$$$ |$$ |  $$ |$$ /  $$ |'
echo ' $$  $$< $$  __$$ |$$ |  $$ |$$  __$$ |$$ |  $$ |$$ |  $$ |'
echo '$$  /\$$\\$$$$$$$ |$$ |  $$ |\$$$$$$$ |\$$$$$$  |\$$$$$$$ |'
echo '\__/  \__|\_______|\__|  \__| \_______| \______/  \_______|'
echo ""
echo ">>> TESTNET EDITION"
echo ">>> HOOKS V3 TESTNET"
echo ""
echo ">>> NETWORK ID: [ 21338 ]"
echo ""

self(){
  DIR=$( cd "$( dirname "$0" )/" && pwd)
  echo $DIR
}

docker rm -f xahaud-testnet

docker run \
    -dit \
    --privileged \
    --cgroupns=host -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
    --name xahaud-testnet \
    -p 2222:22 \
    -p 21338:21338 \
    -p 15005:15005 \
    -p 16005:16005 \
    -p 16006:16006 \
    -p 16007:16007 \
    -v $(self)/./store/db:/opt/xahaud/db \
    -v $(self)/./store/etc:/opt/xahaud/etc \
    -v $(self)/./store/log:/opt/xahaud/log \
    -v $(self)/./store/ssh/authorized_keys:/root/.ssh/authorized_keys \
    xahaud:testnet

echo ""
echo "Xahaud running binary version:"
docker exec xahaud-testnet sh -c 'cat /opt/xahaud/bin/xahaud|md5sum'|cut -d " " -f 1
echo "Xahaud runnin version string (build_version):"
docker exec xahaud-testnet xahaud -q server_info|grep build_version|cut -d '"' -f 4
echo ""